"""Where did this document's number come from?

Answers, for one document and one field, the question this app gets asked most
often: "the number is wrong / it looks calculated — where is it coming from?"
It classifies the stored value (generated by a rule? copied from a legacy field?
a mirror of the document name? typed in?), names the rule and the series counter
behind it, points at the Data Import row or the Version entry that wrote it, and
flags the failure mode that bit us on 2026-08-03: an incoming number silently
discarded because another document already held it.

Read-only. `_build_from_segments(commit_series=False)` peeks the counter without
drawing, and nothing else writes — safe to run on a live site.

Run:
    bench --site <site> console
    >>> from avinashgroup_app.scripts.trace_number import trace, trace_url
    >>> trace("Sales Invoice", "NGK-SRTN-78/79-00417")
    >>> trace_url("https://.../app/sales-invoice/NGK-SRTN-78%2F79-00417")

    # any field, not just the engine's target
    >>> trace("Journal Entry", "NGI-JE-82/83-00001", field="custom_name")

Not through `bench execute` — RestrictedPython rejects the engine's private
helpers (see CLAUDE.md).
"""

import json
from urllib.parse import unquote, urlparse

import frappe

from avinashgroup_app.custom_code.Override import naming_series as ns

# Fields that habitually carry the old ERP's number on this site. Checked as
# possible SOURCES for the stored value, on top of the rule's own
# legacy_source_field.
LEGACY_HINT_FIELDS = ("custom_fact_numbering", "custom_return_against_fact", "narration")

_IDENT = "{0:<14}"


def trace_url(url, field=None):
    """Same as trace(), from a desk URL (/app/sales-invoice/NGK-SRTN-78%2F79-00417)."""
    parts = [p for p in urlparse(url).path.split("/") if p]
    if len(parts) < 3 or parts[0] != "app":
        frappe.throw("Not a desk document URL: {0}".format(url))
    slug, name = parts[1], unquote(parts[2])
    doctype = slug.replace("-", " ").title()
    if not frappe.db.exists("DocType", doctype):
        match = frappe.get_all(
            "DocType", filters={"name": ["like", slug.replace("-", " ")]}, pluck="name", limit=1
        )
        if not match:
            frappe.throw("Cannot resolve doctype from slug '{0}'".format(slug))
        doctype = match[0]
    return trace(doctype, name, field=field)


def trace(doctype, name, field=None):
    if not frappe.db.exists(doctype, name):
        frappe.throw("{0} {1} does not exist on this site".format(doctype, name))
    doc = frappe.get_doc(doctype, name)
    rules = ns._matching_numbering_rules(doc)
    field = field or _default_field(doc, rules)
    value = doc.get(field) if field else None

    _print_identity(doc)
    print("")
    print("FIELD  {0} = {1}".format(field, "None" if value is None else repr(value)))
    print("")

    verdict = _classify(doc, field, value, rules)
    print("")
    _print_writers(doc, field)
    print("")
    _print_rules(doc, rules)
    return verdict


# ---------------------------------------------------------------- identity
def _print_identity(doc):
    print("{0} {1}".format(doc.doctype, doc.name))
    for f in ("company", "custom_branch", "posting_date", "transaction_date",
              "is_return", "docstatus", "amended_from"):
        if doc.meta.has_field(f) or f == "docstatus":
            v = doc.get(f)
            if v not in (None, ""):
                print("  " + _IDENT.format(f) + str(v))
    print("  " + _IDENT.format("created") + "{0} by {1}".format(doc.creation, doc.owner))
    if str(doc.modified) != str(doc.creation):
        print("  " + _IDENT.format("modified") + "{0} by {1}".format(doc.modified, doc.modified_by))


def _default_field(doc, rules):
    """The field to trace when the caller didn't name one: the engine's target for
    this document, else whichever number field the doctype carries."""
    for rule in rules:
        target = rule.get("target_field") or "custom_branch_name"
        if doc.meta.has_field(target):
            return target
    for f in ("custom_branch_name", "custom_name", "custom_document_no"):
        if doc.meta.has_field(f):
            return f
    return None


# -------------------------------------------------------------- the verdict
def _classify(doc, field, value, rules):
    """Say what produced the stored value, and — when it looks generated where a
    supplied number was expected — what was discarded to get there."""
    if not field:
        print("VERDICT  no number field on this doctype")
        return {"verdict": "no field"}
    if value in (None, ""):
        print("VERDICT  EMPTY — nothing has written this field")
        return {"verdict": "empty"}
    if value == doc.name:
        print("VERDICT  MIRROR OF THE DOCUMENT NAME")
        print("         no rule produced a value, so set_custom_branch_name fell back")
        print("         to doc.name. The number you see is the naming-series name.")
        return {"verdict": "name mirror"}

    owning = [r for r in rules
              if (r.get("target_field") or "custom_branch_name") == field]
    if not owning:
        print("VERDICT  NOT ENGINE-OWNED — no matching rule targets {0}".format(field))
        print("         the value came from whoever wrote the field (form, import, script);")
        print("         see WRITTEN BY below.")
        return {"verdict": "not engine owned"}

    for rule in owning:
        key, counter = ns._parse_engine_number(doc, rule, value)
        if key:
            print("VERDICT  GENERATED by rule '{0}'".format(rule["name"]))
            print("         the value decomposes into that rule's segments")
            print("  " + _IDENT.format("series") + key)
            print("  " + _IDENT.format("this number") + str(counter))
            print("  " + _IDENT.format("counter now") + str(ns._series_current(key)))
            if _mirrors_the_name(doc, rule):
                print("  " + _IDENT.format("note") +
                      "the rule's prefix IS the document name's prefix, so the")
                print("  " + _IDENT.format("") +
                      "number is taken from the NAME — no counter of its own,")
                print("  " + _IDENT.format("") +
                      "which is why the series counter can read 0.")
            _report_discarded_input(doc, field, value, rule)
            return {"verdict": "generated", "rule": rule["name"],
                    "series": key, "counter": counter}

    for rule in owning:
        src = rule.get("legacy_source_field")
        if src and src != field and frappe.utils.cstr(doc.get(src)).strip() == value:
            print("VERDICT  COPIED from {0} by rule '{1}'".format(src, rule["name"]))
            print("         (legacy window up to {0}; no counter consumed)".format(
                rule.get("legacy_upto")))
            return {"verdict": "copied", "rule": rule["name"], "source": src}

    rule = owning[0]
    print("VERDICT  SUPPLIED — kept exactly as it arrived")
    print("         the value is not this rule's generated shape and not a copy of a")
    print("         source field, so it came in with the write (import row, REST,")
    print("         script) and the engine stored it verbatim.")
    if ns._is_counterless(doc, rule):
        print("         rule '{0}' is counterless here (legacy window / pass-through),".format(
            rule["name"]))
        print("         which is exactly the config that keeps imported numbers.")
    _report_scope(doc, field, value, rule)
    return {"verdict": "supplied", "rule": rule["name"]}


def _mirrors_the_name(doc, rule):
    """True when the rule's resolved prefix is also the document NAME's prefix —
    the NAME-MIRROR path in _build_from_segments, where the voucher takes the
    name's number instead of drawing its own (one series counted once)."""
    try:
        sep = rule.get("separator") or "/"
        resolved, has_number = ns._resolve_segments(doc, rule, sep)
        if not has_number:
            return False
        raw_key = sep.join(r["value"] for r in resolved
                           if not r["num"] and r.get("value")) + sep
        return frappe.utils.cstr(doc.name).startswith(raw_key)
    except Exception:
        return False


def _report_discarded_input(doc, field, value, rule):
    """The 2026-08-03 failure mode: the row DID carry a number, the engine threw it
    away and generated one. Detectable afterwards because the legacy/source field
    still holds what the sheet sent."""
    in_legacy = False
    if rule.get("legacy_upto"):
        d = ns._rule_date(doc, rule)
        in_legacy = bool(d) and frappe.utils.getdate(d) <= frappe.utils.getdate(rule["legacy_upto"])

    candidates = []
    for f in (rule.get("legacy_source_field"),) + LEGACY_HINT_FIELDS:
        if not f or f == field or f in [c[0] for c in candidates]:
            continue
        if not doc.meta.has_field(f):
            continue
        other = frappe.utils.cstr(doc.get(f)).strip()
        if other and other != value:
            candidates.append((f, other))

    if in_legacy:
        print("")
        print("  NOTE  this document is INSIDE the rule's legacy window (legacy_upto"
              " {0},".format(rule.get("legacy_upto")))
        print("        {0} {1}) — there the number is COPIED from {2}, not generated.".format(
            rule.get("date_field") or "posting/transaction date",
            ns._rule_date(doc, rule), rule.get("legacy_source_field")))
        print("        A generated value here means the incoming number was empty or lost.")

    if not candidates:
        return
    print("")
    print("  DISCARDED INPUT — these fields still hold what the write carried:")
    for f, other in candidates:
        print("    {0} = {1}".format(f, repr(other)))
        holder = frappe.db.get_value(
            doc.doctype,
            {field: other, "name": ["!=", doc.name], "docstatus": ["<", 2]},
            ["name", "company"] if doc.meta.has_field("company") else ["name"],
            as_dict=True,
        )
        if not holder:
            print("      free — nothing else holds it, so it can be restored")
            continue
        print("      held by {0}{1}".format(
            holder["name"],
            " ({0})".format(holder.get("company")) if holder.get("company") else ""))
        if doc.meta.has_field("company") and holder.get("company") == doc.get("company"):
            print("      -> SAME company: a genuine duplicate; the value cannot be restored")
            print("         as it stands — the source data has two rows with one number.")
        else:
            print("      -> OTHER company: legal since the 2026-08-04 per-company scope fix.")
            print("         Before it, the engine cleared an incoming number on ANY")
            print("         group-wide match and generated a new one — this is that bug.")


def _report_scope(doc, field, value, rule=None):
    scope = ns._number_scope_filters(doc, field, rule)
    if not scope.get("company"):
        print("  " + _IDENT.format("scope") +
              "group-wide (field is DB-unique, or no company field)")
    elif len(scope) > 1:
        fy = ns.get_fiscal_year_from_date(
            ns._rule_date(doc, rule) if rule else ns._doc_date(doc))
        print("  " + _IDENT.format("scope") +
              "per company + fiscal year ({0} / {1})".format(doc.get("company"), fy))
    else:
        print("  " + _IDENT.format("scope") +
              "per company ({0}) — fiscal year unresolved".format(doc.get("company")))
    other = ns._other_doc_with_number(doc, field, rule)
    if other:
        print("  " + _IDENT.format("clash") + "{0} holds the same value IN SCOPE".format(other))


# ------------------------------------------------------------- who wrote it
def _print_writers(doc, field):
    print("WRITTEN BY")
    log = frappe.get_all(
        "Data Import Log",
        filters={"docname": doc.name},
        fields=["data_import", "row_indexes", "success"],
        limit=5,
    ) if frappe.db.exists("DocType", "Data Import Log") else []
    for row in log:
        imp = frappe.db.get_value(
            "Data Import", row["data_import"],
            ["import_file", "status", "payload_count", "submit_after_import"], as_dict=True) or {}
        print("  Data Import  {0}".format(row["data_import"]))
        print("    file       {0}".format(imp.get("import_file")))
        print("    row(s)     {0}   (status {1}, {2} rows in the batch)".format(
            row.get("row_indexes"), imp.get("status"), imp.get("payload_count")))
    if not log:
        print("  no Data Import Log row — this document was not created by an import"
              " (or the log was cleared)")

    versions = frappe.get_all(
        "Version", filters={"ref_doctype": doc.doctype, "docname": doc.name},
        fields=["name", "owner", "creation", "data"], order_by="creation", limit=50)
    touched = []
    for v in versions:
        try:
            data = json.loads(v["data"] or "{}")
        except ValueError:
            continue
        for change in data.get("changed") or []:
            if change and change[0] == field:
                touched.append((v["creation"], v["owner"], change[1], change[2]))
    if touched:
        print("  Version history for {0}:".format(field))
        for creation, owner, old, new in touched:
            print("    {0} by {1}: {2} -> {3}".format(creation, owner, repr(old), repr(new)))
    else:
        print("  no Version row changes {0} — the value is what was written at insert"
              " (Versions record submitted-doc edits, not the insert itself)".format(field))


# ------------------------------------------------------------------- rules
def _print_rules(doc, rules):
    print("RULES MATCHING THIS DOCUMENT (most specific first)")
    if not rules:
        print("  none — the engine leaves this document to the naming series")
        return
    ambiguous = {r["name"] for r in ns._ambiguous_numbering_rules(doc)}
    for i, rule in enumerate(rules, 1):
        target = rule.get("target_field") or "custom_branch_name"
        print("  {0}. {1}{2}".format(i, rule["name"], "   *** TIED / AMBIGUOUS ***"
                                     if rule["name"] in ambiguous else ""))
        print("     target {0}   sep {1}   date_field {2}".format(
            target, repr(rule.get("separator") or "/"), rule.get("date_field")))
        if rule.get("legacy_upto"):
            print("     legacy: up to {0}, number copied from {1}".format(
                rule["legacy_upto"], rule.get("legacy_source_field")))
        if rule.get("conditions"):
            print("     when: {0}".format(", ".join(
                "{0}={1}".format(c["field"], c["value"]) for c in rule["conditions"])))
        print("     segments: {0}".format(_segments_text(rule)))
        preview = _peek(doc, rule)
        if preview:
            print("     would produce now: {0}".format(preview))


def _segments_text(rule):
    out = []
    for s in rule.get("segments") or []:
        t = s.get("segment_type")
        if t == "Static Text":
            out.append("'{0}'".format(s.get("static_value")))
        elif t == "Normal / Return Code":
            out.append("Code({0}/{1})".format(s.get("static_value"), s.get("return_value")))
        elif t == "Number":
            out.append("Number({0})".format(s.get("number_length")))
        elif t in ("Document Field", "Fetch from Link"):
            out.append("{0}({1}{2})".format(t, s.get("field"),
                                            "." + s["fetch_field"] if s.get("fetch_field") else ""))
        else:
            out.append(t)
    return " | ".join(out) or "(none)"


def _peek(doc, rule):
    """What the rule would produce for this document right now — nothing drawn."""
    try:
        return ns._build_from_segments(doc, rule, commit_series=False)
    except Exception as e:
        return "<preview failed: {0}>".format(e)


# ------------------------------------------------------- bulk / pattern sweep
def find_regenerated(doctype="Sales Invoice", field="custom_branch_name",
                     source="custom_fact_numbering", limit=20):
    """Every document whose stored number looks GENERATED while `source` still
    holds a different value — i.e. an incoming number that was discarded.
    This is the query that found the 417 NGK returns."""
    if not (frappe.db.has_column(doctype, field) and frappe.db.has_column(doctype, source)):
        print("{0} has no {1} / {2} column".format(doctype, field, source))
        return []
    col_re = r"^[A-Za-z]+-[A-Za-z]+-[0-9]{4,}-"     # ABBR-CODE-nnnnnn-...
    rows = frappe.db.sql(
        """
        SELECT name, company, {field} AS stored, {source} AS supplied
        FROM `tab{dt}`
        WHERE IFNULL({source}, '') != ''
          AND {field} != {source}
          AND {field} REGEXP %s
        ORDER BY company, name
        """.format(dt=doctype, field=field, source=source),
        col_re, as_dict=True,
    )
    print("{0} document(s) hold a generated number while {1} holds another value".format(
        len(rows), source))
    for r in rows[:limit]:
        print("  {0:28} {1:26} <- supplied {2}".format(r.name, r.stored, r.supplied))
    if len(rows) > limit:
        print("  ... {0} more".format(len(rows) - limit))
    return rows
