"""Bulk add or remove one holiday across many Holiday Lists.

Seven companies, and each of them keeps two lists for a fiscal year: the common
one every employee inherits from the Company, and a women-only copy carrying the
extra days (Teej, and by decision of the 2026-09-15 policy meeting, International
Women's Day). That is fourteen lists for FY 83/84 alone.

A holiday the government announces mid-year, or a festival date the client
corrects, therefore has to be typed fourteen times. The list that gets missed is
not discovered until payroll: everyone on it is marked Absent on a day the rest
of the group had off, and the salary slip deducts the day.

Entry point is the `Holiday Bulk Update` single doctype, which calls
`apply_holiday_change()` from its Apply button.

Deliberately narrow:
  * it edits Holiday List rows only. Attendance already marked for that date is
    NOT re-marked — repairing those days belongs to Attendance Fix, which knows
    how to re-read the checkins.
  * it never creates or deletes a Holiday List, so the per-company/per-women
    structure can only be changed deliberately, by hand.
  * it ignores weekly-off rows. Saturdays are generated by the Holiday List's own
    "Add to Holidays" button and are not a per-date decision.
"""

import frappe
from frappe import _
from frappe.utils import getdate

# The women-only copy of a company's list is identified by this suffix on the
# Holiday List *title*, e.g. "NGI 83/84 (Women)". The record name is a numbered
# series (NGI-Holiday-00005), so the title is the only thing that carries intent.
WOMEN_LIST_SUFFIX = " (Women)"


def get_target_lists(companies=None, scope="both"):
    """Holiday Lists to act on.

    `companies` None means every company. `scope` is "both", "women" (only the
    women-only copies) or "common" (only the lists every employee inherits).
    Returns dicts with name, title, company and the date range, so the caller can
    report per list.
    """
    filters = {}
    if companies:
        filters["custom_company"] = ["in", companies]

    lists = frappe.get_all(
        "Holiday List",
        filters=filters,
        fields=["name", "holiday_list_name", "custom_company", "from_date", "to_date"],
        order_by="custom_company asc, holiday_list_name asc",
    )
    if scope == "women":
        return [d for d in lists if is_women_list(d.holiday_list_name)]
    if scope == "common":
        return [d for d in lists if not is_women_list(d.holiday_list_name)]
    return lists


def is_women_list(holiday_list_title):
    return (holiday_list_title or "").endswith(WOMEN_LIST_SUFFIX)


def apply_holiday_change(action, holiday_date, description=None, companies=None, scope="both"):
    """Add or remove `holiday_date` on every target list. Returns a report.

    Raises if the action is unknown or a date is missing, so a mistyped call
    fails at the boundary instead of half-editing fourteen lists.

    A list is skipped, with the reason recorded, when the date falls outside its
    range (a list for another fiscal year) or when there is nothing to do (the
    date is already there on Add, or absent on Remove).
    """
    if action not in ("Add Holiday", "Remove Holiday"):
        frappe.throw(_("Unknown action {0}").format(action))
    if not holiday_date:
        frappe.throw(_("Holiday Date is required"))
    if action == "Add Holiday" and not description:
        frappe.throw(_("Description is required when adding a holiday"))

    holiday_date = getdate(holiday_date)
    changed, skipped = [], []

    for row in get_target_lists(companies, scope):
        doc = frappe.get_doc("Holiday List", row.name)
        label = f"{doc.holiday_list_name} [{doc.custom_company or '-'}]"

        if not (getdate(doc.from_date) <= holiday_date <= getdate(doc.to_date)):
            skipped.append(f"{label}: outside {doc.from_date} — {doc.to_date}")
            continue

        existing = [h for h in doc.holidays if getdate(h.holiday_date) == holiday_date]

        if action == "Add Holiday":
            if existing:
                skipped.append(f"{label}: already has {holiday_date}")
                continue
            doc.append("holidays", {"holiday_date": holiday_date, "description": description})
        else:
            if not existing:
                skipped.append(f"{label}: no holiday on {holiday_date}")
                continue
            # Weekly offs are generated in bulk, never removed one date at a time.
            if all(h.weekly_off for h in existing):
                skipped.append(f"{label}: {holiday_date} is a weekly off")
                continue
            doc.holidays = [h for h in doc.holidays if getdate(h.holiday_date) != holiday_date or h.weekly_off]

        doc.save()
        changed.append(f"{label}: {len(doc.holidays)} holidays")

    return {"action": action, "date": str(holiday_date), "changed": changed, "skipped": skipped}
