"""Add or remove one holiday across many Holiday Lists at once.

Seven companies, each keeping two lists per fiscal year — the common one every
employee inherits from the Company and a women-only copy carrying the extra days
(Teej, International Women's Day). Fourteen lists for FY 83/84.

A holiday the government announces mid-year, or a festival date the client
corrects, otherwise has to be typed into every list by hand. The one that gets
missed is not discovered until payroll, when everyone on it is marked Absent on a
day the rest of the group had off.

Desk entry point is the `Holiday Bulk Update` doctype, which holds the holiday
and the chosen lists and calls `apply_holiday_change()`.

Deliberately narrow:
  * it edits Holiday List rows only. Attendance already marked for that date is
    NOT re-marked — Attendance Fix owns that, because it knows how to re-read the
    checkins.
  * it never creates or deletes a Holiday List, so the per-company structure can
    only change deliberately, by hand.
  * it leaves weekly-off rows alone. Saturdays are generated by the Holiday
    List's own "Add to Holidays" button, not decided per date.
"""

import frappe
from frappe import _
from frappe.utils import getdate

# Separates the date from the name in a removal option. An em dash, so it cannot
# collide with the hyphens inside the date itself.
OPTION_SEPARATOR = "—"


def get_all_list_names():
	"""Every Holiday List, company order — what "All Holiday Lists" means."""
	return frappe.get_all(
		"Holiday List",
		fields=["name", "holiday_list_name", "custom_company", "from_date", "to_date"],
		order_by="custom_company asc, holiday_list_name asc",
	)


def get_removable_holidays(holiday_lists=None):
	"""Dated holidays present in the given lists, newest first, as one option each.

	Removal is picked from this instead of typed: the date alone is easy to get
	wrong, and a date nobody put in any list produces a run that skips fourteen
	times and changes nothing. Weekly offs are left out — Saturdays are generated
	in bulk and are not removed one date at a time.

	Option format is "YYYY-MM-DD — Description"; `holiday_date_from_option()`
	reads the date back out.
	"""
	filters = {"weekly_off": 0}
	if holiday_lists:
		filters["parent"] = ["in", holiday_lists]

	rows = frappe.get_all(
		"Holiday",
		filters=filters,
		fields=["holiday_date", "description"],
		order_by="holiday_date asc",
	)
	seen, options = set(), []
	for row in rows:
		# The same festival sits in many lists; offer it once.
		label = f"{row.holiday_date} {OPTION_SEPARATOR} {frappe.utils.strip_html(row.description or '').strip()}"
		if label not in seen:
			seen.add(label)
			options.append(label)
	return options


def holiday_date_from_option(option):
	"""Date out of an option made by `get_removable_holidays()`."""
	return getdate((option or "").split(OPTION_SEPARATOR)[0].strip())


def apply_holiday_change(action, holiday_date, description=None, holiday_lists=None):
	"""Add or remove `holiday_date` on each named list. Returns a per-list report.

	`holiday_lists` None means every Holiday List. Raises on an unknown action or
	a missing date, so a mistyped call fails at the boundary instead of
	half-editing the set.

	A list is skipped, with the reason recorded, when the date falls outside its
	range (a list for another fiscal year), or when there is nothing to do: the
	date is already there on Add, or not there on Remove.
	"""
	if action not in ("Add Holiday", "Remove Holiday"):
		frappe.throw(_("Unknown action {0}").format(action))
	if not holiday_date:
		frappe.throw(_("Holiday Date is required"))
	if action == "Add Holiday" and not description:
		frappe.throw(_("Holiday name is required when adding"))

	holiday_date = getdate(holiday_date)
	rows = (
		get_all_list_names()
		if not holiday_lists
		else frappe.get_all(
			"Holiday List",
			filters={"name": ["in", holiday_lists]},
			fields=["name", "holiday_list_name", "custom_company", "from_date", "to_date"],
			order_by="custom_company asc, holiday_list_name asc",
		)
	)

	changed, skipped = [], []
	for row in rows:
		doc = frappe.get_doc("Holiday List", row.name)
		label = doc.holiday_list_name

		if not (getdate(doc.from_date) <= holiday_date <= getdate(doc.to_date)):
			skipped.append(f"{label}: outside {doc.from_date} — {doc.to_date}")
			continue

		existing = [h for h in doc.holidays if getdate(h.holiday_date) == holiday_date]

		if action == "Add Holiday":
			if existing:
				skipped.append(f"{label}: already has this date")
				continue
			doc.append("holidays", {"holiday_date": holiday_date, "description": description})
		else:
			if not existing:
				skipped.append(f"{label}: nothing on this date")
				continue
			if all(h.weekly_off for h in existing):
				skipped.append(f"{label}: weekly off")
				continue
			doc.holidays = [
				h for h in doc.holidays if getdate(h.holiday_date) != holiday_date or h.weekly_off
			]

		doc.save()
		changed.append(f"{label}: now {len(doc.holidays)} holidays")

	return {"changed": changed, "skipped": skipped}
